// web/src/components/CartSummary.vue
<template>
    <div>
      <h2 class="text-lg font-semibold mb-4">Resumo do Carrinho</h2>
      <div class="flex flex-col space-y-2">
        <div class="flex justify-between">
          <p class="text-gray-600">Subtotal:</p>
          <p class="text-gray-800 font-semibold">{{ formatCurrency(cartTotal) }}</p>
        </div>
        <div class="flex justify-between">
          <p class="text-gray-600">Custo de Envio:</p>
          <p class="text-gray-800 font-semibold">{{ formatCurrency(shippingCost) }}</p>
        </div>
        <div v-if="discountDetails" class="flex justify-between">
          <p class="text-gray-600">Desconto:</p>
          <p class="text-green-500 font-semibold">{{ formatCurrency(discountDetails.amount) }} ({{ discountDetails.description }})</p>
        </div>
        <div class="flex justify-between">
          <p class="text-gray-600">Total:</p>
          <p class="text-black font-semibold">{{ formatCurrency(cartTotal + shippingCost - (discountDetails ? discountDetails.amount : 0)) }}</p>
        </div>
      </div>
    </div>
  </template>
  
  <script>
  export default {
    props: {
      cartTotal: {
        type: Number,
        required: true
      },
      shippingCost: {
        type: Number,
        required: true
      },
      discountDetails: Object
    },
    methods: {
      formatCurrency(value) {
        return `$${value.toFixed(2)}`;
      }
    }
  };
  </script>
  
  <style scoped>
  /* Estilos para o resumo do carrinho */
  </style>

// web/src/components/cart/CartSummary.tsx
import React from "react";

type Props = {
	cartTotal: number;
	shippingCost: number;
	discountDetails: any;
};

const CartSummary = ({ cartTotal, shippingCost, discountDetails }: Props) => {
	const discount = discountDetails
		? discountDetails.type === "fixed"
			? discountDetails.value
			: (discountDetails.value / 100) * cartTotal
		: 0;
	const total = cartTotal + shippingCost - discount;

	return (
		<div>
			<p>Total do carrinho: R${cartTotal.toFixed(2)}</p>
			<p>Custo de envio: R${shippingCost.toFixed(2)}</p>
			{discountDetails && <p>Desconto: R${discount.toFixed(2)}</p>}
			<p>Total: R${total.toFixed(2)}</p>
		</div>
	);
};

export default CartSummary;
