// web/src/components/CouponForm.vue
<template>
  <div>
    <h2 class="text-lg font-semibold mb-4">Formulário de Cupom</h2>
    <form @submit.prevent="applyCoupon" class="flex items-center">
      <input v-model="couponCode" type="text" placeholder="Digite o código do cupom" class="w-64 p-2 border border-gray-200 rounded-l">
      <button type="submit" class="bg-blue-500 text-white py-2 px-4 rounded-r">Aplicar Cupom</button>
    </form>
  </div>
</template>

<script lang="ts">
export default {
  data() {
    return {
      couponCode: ''
    };
  },
  methods: {
    applyCoupon() {
      this.$emit('applyCoupon', this.couponCode);
    }
  }
};
</script>

<style scoped>
/* Estilos para o formulário de cupom */
</style>

// web/src/components/cart/CouponForm.tsx
import React, { useState } from "react";

type Props = {
	applyCoupon: (couponCode: string) => void;
	couponApplied: boolean;
	loading: boolean;
	message: string;
	success: boolean;
};

const CouponForm = ({
	applyCoupon,
	couponApplied,
	loading,
	message,
	success,
}: Props) => {
	const [couponCode, setCouponCode] = useState("");

	const handleApplyCoupon = () => {
		if (couponCode) {
			applyCoupon(couponCode);
		}
	};

	return (
		<div>
			<input
				type="text"
				value={couponCode}
				onChange={(e) => setCouponCode(e.target.value)}
				placeholder="Código do cupom"
			/>
			<button
				onClick={handleApplyCoupon}
				disabled={loading || couponApplied}
				className="px-4 py-2 bg-blue-500 text-white rounded"
			>
				Aplicar Cupom
			</button>
			{message && (
				<p className={`mt-2 ${success ? "text-green-500" : "text-red-500"}`}>
					{message}
				</p>
			)}
		</div>
	);
};

export default CouponForm;
