// pages/perguntas-frequentes.vue
<script setup lang="ts">
import { computed, ref } from "vue";

interface FAQ {
	id: number;
	header: string;
	text: string;
}

const header = "How long we deliver your first blog post?";
const text =
	"It takes 2-3 weeks to get your first blog post ready. That includes the in-depth research & creation of your monthly content marketing strategy that we do before writing your first blog post, Ipsum available .";

const faqs = ref<FAQ[]>([
	{
		id: 1,
		header,
		text,
	},
	{
		id: 2,
		header,
		text,
	},
	{
		id: 3,
		header,
		text,
	},
	{
		id: 4,
		header,
		text,
	},
	{
		id: 5,
		header,
		text,
	},
	{
		id: 6,
		header,
		text,
	},
]);

const activeFaq = ref<number | null>(null);

const oddFaqs = computed(() => faqs.value.filter((faq) => faq.id % 2 !== 0));
const evenFaqs = computed(() => faqs.value.filter((faq) => faq.id % 2 === 0));

const handleToggle = (faqId: number) => {
	activeFaq.value = activeFaq.value === faqId ? null : faqId;
};
</script>

<template>
  <section
    class="relative z-20 overflow-hidden bg-white dark:bg-dark pt-20 pb-12 lg:pt-[120px] lg:pb-[90px]"
  >
    <div class="container mx-auto">
      <div class="-mx-4 flex flex-wrap">
        <div class="w-full px-4">
          <div class="mx-auto mb-[60px] max-w-[520px] text-center lg:mb-20">
            <span class="mb-2 block text-lg font-semibold text-primary"> FAQ </span>
            <h2
              class="mb-4 text-3xl font-bold text-dark dark:text-white sm:text-[40px] sm:leading-[48px]"
            >
              Any Questions? Look Here
            </h2>
            <p class="text-base text-body-color dark:text-dark-6">
              There are many variations of passages of Lorem Ipsum available but the majority have
              suffered alteration in some form.
            </p>
          </div>
        </div>
      </div>

      <div class="-mx-4 flex flex-wrap">
        <div class="w-full px-4 lg:w-1/2">
          <template :key="faq.id" v-for="faq in oddFaqs">
            <div
              class="mb-8 w-full rounded-lg bg-white p-4 shadow-[0px_20px_95px_0px_rgba(201,203,204,0.30)] dark:bg-dark-2 dark:shadow-[0px_20px_95px_0px_rgba(0,0,0,0.30)] sm:p-8 lg:px-6 xl:px-8"
            >
              <button class="faq-btn flex w-full text-left" @click="handleToggle(faq.id)">
                <div
                  class="mr-5 flex h-10 w-full max-w-[40px] items-center justify-center rounded-lg bg-primary/5 text-primary dark:bg-white/5"
                >
                  <svg
                    class="fill-primary stroke-primary duration-200 ease-in-out"
                    :class="{ 'rotate-180': activeFaq === faq.id }"
                    width="17"
                    height="10"
                    viewBox="0 0 17 10"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M7.28687 8.43257L7.28679 8.43265L7.29496 8.43985C7.62576 8.73124 8.02464 8.86001 8.41472 8.86001C8.83092 8.86001 9.22376 8.69083 9.53447 8.41713L9.53454 8.41721L9.54184 8.41052L15.7631 2.70784L15.7691 2.70231L15.7749 2.69659C16.0981 2.38028 16.1985 1.80579 15.7981 1.41393C15.4803 1.1028 14.9167 1.00854 14.5249 1.38489L8.41472 7.00806L2.29995 1.38063L2.29151 1.37286L2.28271 1.36548C1.93092 1.07036 1.38469 1.06804 1.03129 1.41393L1.01755 1.42738L1.00488 1.44184C0.69687 1.79355 0.695778 2.34549 1.0545 2.69659L1.05999 2.70196L1.06565 2.70717L7.28687 8.43257Z"
                      fill=""
                      stroke=""
                    />
                  </svg>
                </div>

                <div class="w-full">
                  <h4 class="mt-1 text-lg font-semibold text-dark dark:text-white">
                    {{ faq.header }}
                  </h4>
                </div>
              </button>

              <div v-show="activeFaq === faq.id" class="pl-[62px]">
                <p class="py-3 text-base leading-relaxed text-body-color dark:text-dark-6">
                  {{ faq.text }}
                </p>
              </div>
            </div>
          </template>
        </div>

        <div class="w-full px-4 lg:w-1/2">
          <template :key="faq.id" v-for="faq in evenFaqs">
            <div
              class="mb-8 w-full rounded-lg bg-white p-4 shadow-[0px_20px_95px_0px_rgba(201,203,204,0.30)] dark:bg-dark-2 dark:shadow-[0px_20px_95px_0px_rgba(0,0,0,0.30)] sm:p-8 lg:px-6 xl:px-8"
            >
              <button class="faq-btn flex w-full text-left" @click="handleToggle(faq.id)">
                <div
                  class="mr-5 flex h-10 w-full max-w-[40px] items-center justify-center rounded-lg bg-primary/5 text-primary dark:bg-white/5"
                >
                  <svg
                    class="fill-primary stroke-primary duration-200 ease-in-out"
                    :class="{ 'rotate-180': activeFaq === faq.id }"
                    width="17"
                    height="10"
                    viewBox="0 0 17 10"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M7.28687 8.43257L7.28679 8.43265L7.29496 8.43985C7.62576 8.73124 8.02464 8.86001 8.41472 8.86001C8.83092 8.86001 9.22376 8.69083 9.53447 8.41713L9.53454 8.41721L9.54184 8.41052L15.7631 2.70784L15.7691 2.70231L15.7749 2.69659C16.0981 2.38028 16.1985 1.80579 15.7981 1.41393C15.4803 1.1028 14.9167 1.00854 14.5249 1.38489L8.41472 7.00806L2.29995 1.38063L2.29151 1.37286L2.28271 1.36548C1.93092 1.07036 1.38469 1.06804 1.03129 1.41393L1.01755 1.42738L1.00488 1.44184C0.69687 1.79355 0.695778 2.34549 1.0545 2.69659L1.05999 2.70196L1.06565 2.70717L7.28687 8.43257Z"
                      fill=""
                      stroke=""
                    />
                  </svg>
                </div>

                <div class="w-full">
                  <h4 class="mt-1 text-lg font-semibold text-dark dark:text-white">
                    {{ faq.header }}
                  </h4>
                </div>
              </button>

              <div v-show="activeFaq === faq.id" class="pl-[62px]">
                <p class="py-3 text-base leading-relaxed text-body-color dark:text-dark-6">
                  {{ faq.text }}
                </p>
              </div>
            </div>
          </template>
        </div>
      </div>
    </div>

    <div class="absolute bottom-0 right-0 z-[-1]">
      <svg
        width="1440"
        height="886"
        viewBox="0 0 1440 886"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path
          opacity="0.5"
          d="M193.307 -273.321L1480.87 1014.24L1121.85 1373.26C1121.85 1373.26 731.745 983.231 478.513 729.927C225.976 477.317 -165.714 85.6993 -165.714 85.6993L193.307 -273.321Z"
          fill="url(#paint0_linear)"
        />
        <defs>
          <linearGradient
            id="paint0_linear"
            x1="1308.65"
            y1="1142.58"
            x2="602.827"
            y2="-418.681"
            gradientUnits="userSpaceOnUse"
          >
            <stop stop-color="#3056D3" stop-opacity="0.36" />
            <stop offset="1" stop-color="#F5F2FD" stop-opacity="0" />
            <stop offset="1" stop-color="#F5F2FD" stop-opacity="0.096144" />
          </linearGradient>
        </defs>
      </svg>
    </div>
  </section>
</template>

// web/src/pages/perguntas-frequentes.tsx
import Layout from "@/components/core/Layout";
import React from "react";

type Props = {};

const perguntasFrequentes = (props: Props) => {
	const openFaqs: any[] = [];
	const faqs = [
		{
			question: "Quais são as opções de pagamento disponíveis?",
			answer:
				"Oferecemos diversas opções de pagamento, incluindo cartão de crédito, débito, PayPal e transferência bancária. Você pode escolher a opção que melhor se adequa às suas necessidades.",
		},
		{
			question: "Como faço para acompanhar meu pedido?",
			answer:
				"Assim que seu pedido for despachado, você receberá um e-mail de confirmação com um link para rastrear o status da entrega. Você também pode acessar sua conta e verificar o status do pedido a qualquer momento.",
		},
		{
			question: "Quanto tempo leva para a entrega?",
			answer:
				"O prazo de entrega pode variar dependendo do seu local de entrega e do método de envio escolhido. Normalmente, os pedidos são entregues dentro de 3 a 7 dias úteis após a confirmação do pagamento.",
		},
		{
			question: "Posso devolver um produto se não estiver satisfeito?",
			answer:
				"Sim, aceitamos devoluções dentro de um prazo específico após a entrega do produto, desde que esteja nas condições originais e acompanhado da embalagem original. Consulte nossa política de devolução para obter mais informações.",
		},
		{
			question: "Como faço para entrar em contato com o suporte ao cliente?",
			answer:
				"Você pode entrar em contato com nosso suporte ao cliente por e-mail, telefone ou chat ao vivo. Nossa equipe de atendimento está disponível para ajudar com qualquer dúvida ou problema que você possa ter.",
		},
		// Adicione mais questões conforme necessário
	];
	const toggleFaq = (index: number) => {
		openFaqs[index] = !openFaqs[index];
	};

	return (
		<Layout>
			<section className="relative z-20 overflow-hidden bg-white dark:bg-dark pt-20 pb-12 lg:pt-[120px] lg:pb-[90px]">
				<div className="container mx-auto">
					<div className="flex flex-wrap -mx-4">
						<div className="w-full px-4">
							<div className="mx-auto mb-[60px] max-w-[520px] text-center lg:mb-20">
								<span className="block mb-2 text-lg font-semibold text-primary">
									FAQ
								</span>
								<h2 className="text-dark dark:text-white mb-4 text-3xl font-bold sm:text-[40px]/[48px]">
									Any Questions? Look Here
								</h2>
								<p className="text-base text-body-color dark:text-dark-6">
									There are many variations of passages of Lorem Ipsum available
									but the majority have suffered alteration in some form.
								</p>
							</div>
						</div>
					</div>
					<div className="flex flex-wrap -mx-4">
						{faqs.map((faq, index) => {
							return (
								<div
									className="w-full px-4 lg:w-1/2"
									v-for="(faq, index) in "
									key="index"
								>
									<div className="w-full p-4 mb-8 bg-white rounded-lg shadow-[0px_20px_95px_0px_rgba(201,203,204,0.30)] dark:shadow-[0px_20px_95px_0px_rgba(0,0,0,0.30)] dark:bg-dark-2 sm:p-8 lg:px-6 xl:px-8">
										<button
											className="flex w-full text-left faq-btn"
											onClick={(e) => toggleFaq(index)}
										>
											<div className="bg-primary/5 dark:bg-white/5 text-primary mr-5 flex h-10 w-full max-w-[40px] items-center justify-center rounded-lg">
												<svg
													className="[openFaqs[index] && 'rotate-180']"
													width="22"
													height="22"
													viewBox="0 0 22 22"
													fill="none"
													xmlns="http://www.w3.org/2000/svg"
												>
													<path
														d="M11 15.675C10.7937 15.675 10.6219 15.6062 10.45 15.4687L2.54374 7.69998C2.23436 7.3906 2.23436 6.90935 2.54374 6.59998C2.85311 6.2906 3.33436 6.2906 3.64374 6.59998L11 13.7844L18.3562 6.53123C18.6656 6.22185 19.1469 6.22185 19.4562 6.53123C19.7656 6.8406 19.7656 7.32185 19.4562 7.63123L11.55 15.4C11.3781 15.5719 11.2062 15.675 11 15.675Z"
														fill="currentColor"
													/>
												</svg>
											</div>
											<div className="w-full">
												<h4 className="mt-1 text-lg font-semibold text-dark dark:text-white">
													{faq.question}
												</h4>
											</div>
										</button>
										<div
											v-show="openFaqs[index]"
											className="faq-content pl-[62px]"
										>
											<p className="py-3 text-base leading-relaxed text-body-color dark:text-dark-6">
												{faq.answer}
											</p>
										</div>
									</div>
								</div>
							);
						})}
					</div>
				</div>
			</section>
		</Layout>
	);
};

export default perguntasFrequentes;
