// web/src/components/product/Tabs.vue
<template>
    <div>
      <div class="flex border-b">
        <button
          v-for="tab in tabs"
          :key="tab.value"
          :class="[
            'py-2 px-4 -mb-px text-sm focus:outline-none',
            tab.value === selectedTab
              ? 'border-b-2 border-indigo-500 text-indigo-500'
              : 'border-b-2 border-transparent text-gray-500 hover:text-gray-700'
          ]"
          @click="selectTab(tab.value)"
        >
          {{ tab.name }}
        </button>
      </div>
    </div>
  </template>
  
  <script lang="ts">
  export default {
    props: {
      tabs: {
        type: Array,
        required: true,
      } as any,
      selectedTab: {
        type: String,
        required: true,
      },
    },
    methods: {
      selectTab(value: string) {
        this.$emit('selectTab', value);
      },
    },
  };
  </script>
  
  <style scoped>
  /* Seu estilo aqui */
  </style>

// web/src/components/product/Tabs.tsx
import React from "react";

type Props = {
	tabs: { name: string; value: string }[];
	selectedTab: string;
	selectTab: (tab: string) => void;
};

const Tabs = ({ tabs, selectedTab, selectTab }: Props) => {
	return (
		<div className="tabs">
			{tabs.map((tab) => (
				<button
					key={tab.value}
					className={`tab ${selectedTab === tab.value ? "active" : ""}`}
					onClick={() => selectTab(tab.value)}
				>
					{tab.name}
				</button>
			))}
		</div>
	);
};

export default Tabs;
