// web/src/components/core/Checkbox.tsx
import React from "react";

type Props = {};

const Checkbox = (props: Props) => {
	return (
		<label className="flex items-center space-x-2 cursor-pointer">
			<input
				type="checkbox"
				className="form-checkbox h-5 w-5 text-purple-600 dark:text-purple-400 border-gray-300 dark:border-gray-700 rounded"
				checked={false}
			/>
			<span className="text-sm text-body-color dark:text-gray-300"></span>
		</label>
	);
};

export default Checkbox;

// components/core/Checkbox.vue
<script setup lang="ts">
import { ref } from "vue";

const isChecked = ref(false);

const handleCheckboxChange = () => {
	isChecked.value = !isChecked.value;
};
</script>

<template>
  <label class="flex items-center cursor-pointer select-none text-dark dark:text-white">
    <div class="relative">
      <input type="checkbox" class="sr-only" @change="handleCheckboxChange" />
      <div
        class="box mr-4 flex h-5 w-5 items-center justify-center rounded border-stroke dark:border-dark-3 border"
      >
        <span :class="{ '!bg-purple-500': isChecked }" class="dot h-[10px] w-[10px] rounded-sm"></span>
      </div>
    </div>
    <slot />
  </label>
</template>
