// web/src/components/cart/CartItemList.tsx
import React from "react";

type Props = {
	cartItems: any[];
	removeItem: (id: number) => void;
};

const CartItemList = ({ cartItems, removeItem }: Props) => {
	return (
		<div>
			{cartItems.map((item) => (
				<div key={item.id} className="flex justify-between items-center">
					<div>
						<h2>{item.name}</h2>
						<p>Quantidade: {item.quantity}</p>
						<p>Preço: R${item.price}</p>
					</div>
					<button onClick={() => removeItem(item.id)}>Remover</button>
				</div>
			))}
		</div>
	);
};

export default CartItemList;

// web/src/components/CartItemList.vue
<template>
    <div>
      <h2 class="text-lg font-semibold mb-4">Itens do Carrinho</h2>
      <ul>
        <li v-for="item in cartItems" :key="item.id" class="py-2 border-b border-gray-200">
          <div class="flex justify-between items-center">
            <div class="flex items-center">
              <img :src="item.image" alt="Product Image" class="w-12 h-12 mr-4">
              <div>
                <h3 class="text-base font-semibold">{{ item.name }}</h3>
                <p class="text-gray-600">{{ item.quantity }} x {{ formatCurrency(item.price) }}</p>
              </div>
            </div>
            <button @click="removeItem(item.id)" class="text-red-500 font-semibold">Remover</button>
          </div>
        </li>
      </ul>
    </div>
  </template>
  
  <script lang="ts">
  export default {
    props: {
      cartItems: {
        type: Array,
        required: true
      }
    },
    methods: {
      removeItem(itemId) {
        this.$emit('removeItem', itemId);
      },
      formatCurrency(value) {
        return `$${value.toFixed(2)}`;
      }
    }
  };
  </script>
  
  <style scoped>
  /* Estilos para a lista de itens do carrinho */
  </style>
