// web/src/components/Newsletter.tsx
import axiosClient from "@/utils/axiosClient";
import React, { useRef, useState } from "react";
import Input from "./core/Input";
import Button from "./core/Button";

type Props = {};

const Newsletter = (props: Props) => {
	const [email, setEmail] = useState("");
	const [error, setError] = useState({
		email: "",
		emailRegex: "",
		general: "",
	});
	const [success, setSuccess] = useState("");
	const [loading, setLoading] = useState(false);
	const emailRef = useRef<HTMLInputElement | null>(null);

	const closeSuccess = () => {
		setTimeout(() => {
			setSuccess("");
		}, 5000);
	};

	const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
		event.preventDefault();
		if (!email) {
			setError({ ...error, email: "Por favor digite seu email." });
			emailRef.current?.focus();
			return;
		}
		if (!/^\S+@\S+\.\S+$/.test(email)) {
			setError({
				...error,
				email: "",
				emailRegex: "Formato de email inválido.",
			});
			emailRef.current?.focus();
			return;
		}

		setLoading(true);
		axiosClient
			.post("/newsletter/subscribe", { email })
			.then((response) => {
				setLoading(false);
				setSuccess("Inscrição realizada com sucesso!");
				setEmail("");
				setError({ email: "", emailRegex: "", general: "" });
				closeSuccess();
			})
			.catch((error) => {
				setLoading(false);
				setSuccess("");
				setError({
					...error,
					general: "Ocorreu um erro ao realizar a inscrição.",
				});
			});
	};

	return (
		<section className="bg-sandstorm bg-[url('/grafico_apoio_amarelo.png')] py-12 md:py-16 bg-fixed bg-cover bg-no-repeat">
			<div className="container mx-auto max-w-2xl px-4 md:px-6">
				<div className="space-y-6 text-center">
					<h2 className="text-2xl font-bold md:text-3xl">
						Mantenha-se atualizado com nossas últimas notícias e ofertas
					</h2>
					<p className="text-muted-foreground">
						Assine nossa newsletter e seja o primeiro a saber sobre nossos novos
						produtos, ofertas exclusivas e muito mais.
					</p>
					<form
						className="flex flex-col md:flex-row md:items-start gap-4"
						onSubmit={handleSubmit}
					>
							<Input
								type="email"
								placeholder="Digite seu email"
								className="w-full px-4 py-2 border rounded-tl-lg rounded-b-lg focus:outline-none focus:ring-2 focus:ring-midnight"
								value={email}
								onChange={(e) => setEmail(e.target.value)}
								ref={emailRef}
								name={"newsletter-input"}
								error={error.email || error.emailRegex || error.general}
							/>
						<Button
							type="submit"
							disabled={loading}
							className="md:w-1/2"
						>
							{loading ? <LoadingSpinner /> : "Assinar"}
						</Button>
						{success && (
							<span className="text-electric-blue text-center pt-2">
								{success}
							</span>
						)}
					</form>
				</div>
			</div>
		</section>
	);
};

const LoadingSpinner = () => (
	<div className="w-5 h-5 border-2 border-t-2 border-off-white rounded-full animate-spin"></div>
);

export default Newsletter;

// web/src/components/Newsletter.vue
<template>
	<div id="newsletter" class="py-8 bg-gray-100">
	  <!-- container -->
	  <div class="container mx-auto">
		<!-- row -->
		<div class="flex justify-center">
		  <div class="w-full md:w-8/12 lg:w-6/12 px-4">
			<div class="newsletter bg-white p-8 rounded-lg shadow-md">
			  <p class="text-lg font-bold mb-4">Cadastre-se para receber a <strong>NEWSLETTER</strong></p>
			  <form @submit.prevent="subscribe">
				<input v-model="email" class="input w-full border border-gray-300 rounded-lg px-4 py-2 mb-4 focus:outline-none focus:border-blue-500" type="email" placeholder="Digite seu e-mail" required>
				<button type="submit" class="newsletter-btn bg-blue-500 hover:bg-blue-600 text-white rounded-lg px-4 py-2 focus:outline-none"><i class="fa fa-envelope"></i> Inscrever-se</button>
				<p v-if="errorMessage" class="text-red-500 mt-2">{{ errorMessage }}</p>
			  </form>
			  <ul class="newsletter-follow flex justify-center mt-4">
				<li class="mr-4">
				  <a href="#" class="text-gray-500 hover:text-blue-500"><i class="fa fa-facebook"></i></a>
				</li>
				<li class="mr-4">
				  <a href="#" class="text-gray-500 hover:text-blue-500"><i class="fa fa-twitter"></i></a>
				</li>
				<li class="mr-4">
				  <a href="#" class="text-gray-500 hover:text-blue-500"><i class="fa fa-instagram"></i></a>
				</li>
				<li>
				  <a href="#" class="text-gray-500 hover:text-blue-500"><i class="fa fa-pinterest"></i></a>
				</li>
			  </ul>
			</div>
		  </div>
		</div>
		<!-- /row -->
	  </div>
	  <!-- /container -->
	</div>
  </template>
  
  <script lang="ts">
  import axios from 'axios';
  
  export default {
	name: 'NewsletterView',
	data() {
	  return {
		email: '',
		errorMessage: ''
	  };
	},
	methods: {
	  async subscribe() {
		// Validação do campo de e-mail
		if (!this.email || !this.isValidEmail(this.email)) {
		  this.errorMessage = 'Por favor, insira um e-mail válido.';
		  return;
		}
  
		try {
		  // Enviar a requisição para o servidor usando Axios
		  await axios.post('URL_DO_SERVIDOR', { email: this.email });
		  // Limpar o campo de e-mail e exibir mensagem de sucesso
		  this.email = '';
		  alert('Inscrição realizada com sucesso para o e-mail: ' + this.email);
		  this.errorMessage = '';
		} catch (error) {
		  // Em caso de erro na requisição, exibir mensagem de erro
		  this.errorMessage = 'Ocorreu um erro ao enviar o e-mail. Por favor, tente novamente mais tarde.';
		}
	  },
	  isValidEmail(email: string) {
		// Expressão regular para validar e-mails
		const emailRegex = /\S+@\S+\.\S+/;
		return emailRegex.test(email);
	  }
	}
  };
  </script>
  
  <style scoped>
  /* Estilos para o componente Newsletter */
  </style>
